### ISSUE TITLE
how can i change the  sound output ?

### ISSUE THREAD

**Issue by tonychou1011** [googlecreativelab/teachable-machine#14]
hello ,this is tony from taiwan . I'm a college student . I have some question about your projrct-Teachable Machine . I tried use your source code from github  to change the sound output. But it doesn't work . How can i do to change the output?

**Comment by vagits** [comment]
Hi Tony, have you tried to look for audio file links in the source code.
One you find that you should be able to change the audio file itself and
hence the output.

On Nov 26, 2017 12:58 AM, "tonychou1011" <notifications@github.com> wrote:

hello ,this is tony from taiwan . I'm a college student . I have some
question about your projrct-Teachable Machine . I tried use your source
code from github to change the sound output. But it doesn't work . How can
i do to change the output?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlecreativelab/teachable-machine/issues/14>, or mute
the thread

**Comment by tonychou1011** [comment]
I have changed the audio file links in the source code ,but it's the same as the origin version. The sound output doesn't change .  Does it have some limits about the sound file? Or did i use the wrong way  building the website. Can you give some advice for building it?

**Comment by HalfdanJ** [comment]
There shouldn't be anything hindering you from changing the sound files to your own sounds, others have done so as well. If you push your changes as a fork I can try and take a look.

**Comment by tonychou1011** [comment]
But I have one problem . I amnot familiar with Github . I can't demo it on github . So i tried using other platform to demo it . like Netbeans.  How should i do that i can see the demo on github ?

**Comment by tonychou1011** [comment]
this is my file 
https://github.com/tonychou1011/teachable-machine.git

**Comment by tonychou1011** [comment]
I found what wrong on my file ,and solved my problem , thank you HalfdanJ and vagits !
