### ISSUE TITLE
It prompts me to download and use Chrome, while already using Chrome.

### ISSUE THREAD

**Issue by ryanwellsdotcom** [googlecreativelab/teachable-machine#25]
I do not have ad blockers installed and WebGL Draft Extensions is enabled via 'chrome://flags/':

![image](https://user-images.githubusercontent.com/16037222/38178097-3d182d48-35d9-11e8-81c0-a5cf2fbc4f89.png)

**Comment by HalfdanJ** [comment]
I've experienced a couple of times that WebGL can silently crash on Chrome (and result in this error), and only fix it by restarting Chrome. Does that work for you?

**Comment by ryanwellsdotcom** [comment]
No, restarting Chrome doesn't appear to remedy the issue.

**Comment by INNFINITEMINDS** [comment]
can anyone help me how can i install dependecy of this repo ? i have downloaded this rpeo.
now how to run this ? also i want to run this on offline mode ?
does internet required for running this ?
also i dont want to give only 3 input ! so in order to change the number of inputs and output what and which code i have to modify ?


help reqquired and !!
thanks in advance for helping !

**Comment by 1manthan** [comment]
SomeBody Please help me,
I have downloaded the Zip file, then i have type commands but it show that system didnot recognize as internal, so i have now installed node and npm tool. now what next to do.

pls help me ,I am a begginer  @alexanderchen 
 want to learn ML

**Comment by HalfdanJ** [comment]
Still unclear why webgl might not work on in some browsers, but its outside this codes scope, since its the browser returning that webgl is not working. But the error message is now changed to not be asking to download chrome if chrome is already used. Sorry not to have a better solution.
